### ISSUE TITLE
Feedback: First Challenge Functions

### ISSUE THREAD

**Issue by anselb** [cs1-3-data-struct-and-algos/cs1.3-core-data-structures-and-algos#2]
- It seems that you started using string splices, which is okay, but string splices increase the space complexity of your code (splices create a copy of the string, which dramatically increases space complexity compared to a string search without using splices), so I would recommend refactoring it. 
- Your solution of reusing find_index in find_all_indexes looks pretty good. The list comprehension is cool in find_all_indexes too, but you can also call list() on range() to get the same list.
- You should try to implement the original feedback that I suggested as well, such as fixing your tests cases (and using them) or annotating your strings functions.

**Comment by ThomasLee94** [comment]
done
