### ISSUE TITLE
Feedback: Second Challenge Submission

### ISSUE THREAD

**Issue by anselb** [cs1-3-data-struct-and-algos/cs1.3-core-data-structures-and-algos#3]
- Be careful with your big O notation on built in methods; in ArrayQueue dequeue, deleting the first element in a list is O(n), not O(1). You can read more in the Python [docs](https://docs.python.org/2/tutorial/datastructures.html#using-lists-as-queues). 
- It appears your tests correctly caught an error in your is_subset function. Make sure you are checking that the right set is a subset of the other set. You should also consider adding the size property to your Set even though you could call the hash table size. It's not a big problem though because you have length().
- Your set tests are fine the way they currently are, but you might consider varying the input to use integers or multi-character strings, as I have already seen this break someone's code.

**Comment by ThomasLee94** [comment]
done
